### ISSUE TITLE
Github links (`g#*`) only expand the first in a single message

### ISSUE THREAD

**Issue by mrasband** [pyslackers/sirbot-pyslackers#179]
I'd expect a message with multiple `g#*` messages to expand multiple times, currently it only does the first found occurrence.

https://github.com/pyslackers/sirbot-pyslackers/blob/8a14a415cbc71accefbd6603be6d601067ab1d4d/sirbot-pyslackers/endpoints/slack/messages.py#L289-L306

**Comment by stuartmccoll** [comment]
I'd like to pick this up, if possible 🙂?

**Comment by ovv** [comment]
Hello @stuartmccoll . You can pick that up.
Feel free to ping me (here or on slack) if you have any question

**Comment by stuartmccoll** [comment]
Thanks, I'm still working on it - finally managed to get Ngrok to successfully tunnel to my Docker container. I've noticed a few things that are missing from the documentation in order to get 'up and running', I'll probably raise a separate pull request for those 👍.

**Comment by stuartmccoll** [comment]
Update for @ovv to say I have a branch ready to push for PR 🙂.

**Comment by ovv** [comment]
> I've noticed a few things that are missing from the documentation in order to get 'up and running', I'll probably raise a separate pull request for those +1.

That would be fantastic

>  just need permissions to push

You don't need any permission to push. On github people work via fork and you have all needed permissions on your fork. If you are not familiar with the github flow (this looks like a good introduction https://gist.github.com/Chaser324/ce0505fbed06b947d962).

**Comment by stuartmccoll** [comment]
Thanks, I'll raise the PR this evening 😁.
