### ISSUE TITLE
Stocks: KeyError: 'latestVolume'

### ISSUE THREAD

**Issue by ovv** [pyslackers/sirbot-pyslackers#194]
https://sentry.io/pyslackers/sir-bot-a-lot/issues/748250467/

```
KeyError: 'latestVolume'
  File "sirbot/plugins/slack/endpoints.py", line 114, in _callback
    f.result()
  File "sirbot-pyslackers/endpoints/slack/messages.py", line 164, in stock_quote
    "value": f'{quote["latestVolume"]:,}',

'latestVolume'
```

**Comment by brendonakay** [comment]
Do you think it would be best to use the `.get()` methods for these fields? If you think that's sloppy I can consider a better solution. It seems like there's no determining which could be null from this API.

**Comment by ovv** [comment]
It seems like the best solution. Shame that their API isn't more consistent
