### ISSUE TITLE
Update /snippet slash command to include examples

### ISSUE THREAD

**Issue by daredevil82** [pyslackers/sirbot-pyslackers#230]
The snippet slash command is useful, but I think it can be more useful to summarize some of the code formatting (and other formatting available)

For example, a message like

Please use the snippet feature, or backticks, when sharing code. You can do so by clicking on the ➕  on the left of the input box for a snippet.
Single backticks (`) will format single lines `looking like this`
Triple backticks (```) will format multiple lines ```looking like this```

Question, will these require escaping to display properly in the slack message?

**Comment by ovv** [comment]
Slack updated the location of the snippet feature. The help message needs to be updated for the changes
