### ISSUE TITLE
Support Github "Draft" PRs

### ISSUE THREAD

**Issue by mrasband** [pyslackers/sirbot-pyslackers#244]
Github "Draft" PRs are not necessarily actionable, should we change how these are displayed in the #community_projects channel?

**Comment by ovv** [comment]
What's a draft PR ? 

We could post in a different colour and change it to the usual green when it's not a draft anymore.

**Comment by mrasband** [comment]
Sorry for not including the context: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by ovv** [comment]
sirbot no longer support github & we migrated to github slack app
