### ISSUE TITLE
Feature upgrade - allow currency specification for crypto inquiry

### ISSUE THREAD

**Issue by michjnich** [pyslackers/sirbot-pyslackers#282]
The bot today appends "-USD" automatically. Yahoo supports USD, EUR, and GBP. Allow the user to specify this in the channel and fall back to USD if nothing specified or the currency given is not one of these, meaning resulting code is "as-is", plus extra feature.

eg. `c$BTC-EUR` returns: 
```
BTC-EUR (Bitcoin EUR): €10,761.2010
Change €1,413.8047 (15.1251%)
Volume 32,467,195,904
Open €9,347.3960
Close €9,347.3960
Low €9,345.9140
High €10,761.2010
Today at 9:04 PM
```
(Coding actually already done, just need to submit a pull request if it's a desirable feature ...)

**Comment by mrasband** [comment]
This would be great, thank you!
